site_name: CPTS Writeups
site_url: https://thewzz.github.io/cpts-writeups
site_description: Writeups do curso preparatório CPTS
site_author: Matheus Navarro de Franca

extra_css:
  - stylesheets/extra.css
  - stylesheets/home.css

theme:
  name: material
  language: pt-BR
  custom_dir: docs/overrides
  palette:
    - scheme: slate
      primary: teal
      accent: teal
  features:
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: pt-BR
          name: Português (BR)
          default: true
          build: true
        - locale: en
          name: English
          build: true
          site_name: CPTS Writeups
          site_description: Writeups from the CPTS preparatory course
          theme:
            language: en
          nav_translations:
            Máquinas: Machines
            Índice: Index
            Concluídos: Completed
            Em Andamento: In Progress
            Shells e Payloads - Desafio: Shells and Payloads - Challenge
            Anotações: Notes
            Estudos Footprinting: Footprinting Studies
            SMB Client: SMB Client

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - attr_list

nav:
  - Máquinas:
    - Índice: machines/index.md
    - Concluídos:
      - Easy:
        - Getting Started: machines/getting-started.md
        - Robot: machines/robot.md
        - CAP: machines/cap.md
        - Dancing: machines/dancing.md
        - Redeemer: machines/redeemer.md
        - Footprinting Tests - Easy: machines/footprinting-tests-easy.md
      - Medium:
        - Footprinting Tests - Medium: machines/footprinting-tests-medium.md
        - Shells e Payloads - Desafio: machines/shells-e-payloads-desafio.md
      - Hard:
        - Footprinting Tests - Hard: machines/footprinting-tests-hard.md
    - Em Andamento:
      - Easy:
        - Silentium: machines/silentium.md
        - Facts: machines/facts.md
  - Home: index.md
  - Anotações:
    - Estudos Footprinting:
        - DNS: notes/footprinting/dns.md
        - SMB Client: notes/footprinting/smb-client.md
        - SMTP: notes/footprinting/smtp.md
        - ORACLE TNS: notes/footprinting/oracle-tns.md
        - IPMI: notes/footprinting/ipmi.md