site_name: CPTS Writeups
site_url: https://thewzz.github.io/cpts-writeups
site_description: Writeups do curso preparatório CPTS
site_author: Matheus Navarro de Franca

extra_css:
  - stylesheets/extra.css
  - stylesheets/home.css

theme:
  name: material
  custom_dir: docs/overrides
  icon:
    logo: hacking
  palette:
    - scheme: slate
      primary: teal
      accent: teal
  features:
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - attr_list

nav:
  - Home: index.md
  - Máquinas:
    - Índice: machines/index.md
    - Getting Started: machines/getting-started.md
    - Robot: machines/robot.md
    - HTB Máquinas Ativas: machines/htb-machines.md
  - Anotações:
    - Índice: notes/index.md